name:                purely-effectful
version:             0.1.0.0
github:              "F-Joachim/purely-effectful"
license:             BSD3
author:              Joachim Friedrich
maintainer:          "49515773+F-Joachim@users.noreply.github.com"
copyright:           "2026 Joachim Friedrich"

description:         A Haskell project for demonstrating the Effectful library with Redis, Database, and Logging effects.
language:            GHC2021

dependencies:
  - base >=4.7 && <5

library:
  source-dirs: src
  dependencies:
    - base
    - bytestring
    - containers
    - effectful
    - effectful-core
    - hedis
    - hs-opentelemetry-sdk
    - hs-opentelemetry-propagator-b3
    - hs-opentelemetry-propagator-datadog
    - hs-opentelemetry-api
    - hs-opentelemetry-exporter-otlp
    - hs-opentelemetry-otlp
    - hs-opentelemetry-propagator-w3c
    - text
    - thread-utils-context
    - thread-utils-finalizers

executables:
  purely-effectful-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - purely-effectful
    ghc-options:
      - -threaded
